const express = require("express");

const authMiddleware = require("../middleware/authMiddleware");

const {
  handleBlobUpload,
  uploadFile,
  getFiles,
  getStorageStats,
  renameFile,
  moveFile,
  downloadFile,
  deleteFile,
  getTrash,
  restoreFile,
  restoreFolder,
  searchFilesAndFolders,
  uploadNewVersion,
  getFileVersions,
  downloadFileVersion,
  restoreFileVersion,
  getRecentFiles,
} = require("../controllers/fileController");

const {
  requireEditorAccess,
} = require("../middleware/sharePermission");

const {
  secureDownloadPath,
} = require("../middleware/secureDownload");

const {
  validate,
  fileIdParamsSchema,
  fileVersionParamsSchema,
  getFilesQuerySchema,
  renameFileSchema,
  moveFileSchema,
  searchQuerySchema,
} = require("../middleware/validate");

const router = express.Router();

/* =========================================================
   VERCEL BLOB UPLOAD AUTH
========================================================= */

/*
 * Vercel Blob client uploads use this route for two things:
 *
 * 1. Initial upload-token generation
 *    → Must be authenticated.
 *
 * 2. Vercel's upload-completed callback
 *    → Must NOT use the browser's authentication cookie.
 *
 * The completion callback is authenticated by the signed
 * tokenPayload generated by fileController.handleBlobUpload.
 *
 * Therefore only the completion callback bypasses the normal
 * auth middleware.
 */

const blobUploadAuth = (req, res, next) => {
  /*
   * Vercel Blob sends this type when notifying the application
   * that a client upload has completed.
   *
   * The controller validates the signed token payload and
   * verifies the uploaded Blob before writing metadata to DB.
   */
  if (
    req.body &&
    req.body.type === "blob.upload-completed"
  ) {
    return next();
  }

  /*
   * Initial client upload-token requests must be authenticated.
   */
  return authMiddleware(req, res, next);
};

/* =========================================================
   VERCEL BLOB CLIENT UPLOAD
========================================================= */

/*
 * Actual file bytes are uploaded directly from the browser
 * to Vercel Blob.
 *
 * No file-size limit is imposed here.
 *
 * Flow:
 *
 * Browser
 *   ↓
 * Authenticated token request
 *   ↓
 * Vercel Blob client upload
 *   ↓
 * Vercel Blob
 *   ↓
 * Signed completion callback
 *   ↓
 * PostgreSQL metadata
 */

router.post(
  "/blob-upload",
  blobUploadAuth,
  handleBlobUpload
);

/*
 * Explicit alias retained for compatibility.
 */
router.post(
  "/upload-token",
  blobUploadAuth,
  handleBlobUpload
);

/* =========================================================
   AUTHENTICATED ROUTES
========================================================= */

router.use(
  authMiddleware
);

/* =========================================================
   LEGACY UPLOAD ENDPOINT
========================================================= */

/*
 * Kept for backward compatibility.
 *
 * The new frontend must NOT send file bytes through this
 * endpoint. New uploads use /blob-upload.
 *
 * The controller currently returns the appropriate legacy
 * response instead of attempting to write to the Vercel
 * filesystem.
 */

router.post(
  "/upload",
  uploadFile
);

/* =========================================================
   VERSION UPLOAD
========================================================= */

/*
 * New file versions use direct browser → Vercel Blob
 * uploads through the same Blob handler.
 *
 * clientPayload contains:
 *
 * {
 *   purpose: "version",
 *   fileId: "...",
 *   fileName: "...",
 *   contentType: "..."
 * }
 */

router.post(
  "/:id/versions/upload-token",
  handleBlobUpload
);

/*
 * Legacy multipart version endpoint retained for route
 * compatibility.
 */
router.post(
  "/:id/versions",
  uploadNewVersion
);

/* =========================================================
   VERSION ROUTES
========================================================= */

router.get(
  "/:id/versions",
  validate({
    params:
      fileIdParamsSchema,
  }),
  getFileVersions
);

router.get(
  "/:id/versions/:versionId/download",
  validate({
    params:
      fileVersionParamsSchema,
  }),
  secureDownloadPath(
    "version"
  ),
  downloadFileVersion
);

router.post(
  "/:id/versions/:versionId/restore",
  validate({
    params:
      fileVersionParamsSchema,
  }),
  restoreFileVersion
);

/* =========================================================
   STATIC ROUTES
========================================================= */

router.get(
  "/recent",
  getRecentFiles
);

router.get(
  "/stats",
  getStorageStats
);

router.get(
  "/search",
  validate({
    query:
      searchQuerySchema,
  }),
  searchFilesAndFolders
);

router.get(
  "/trash",
  getTrash
);

router.get(
  "/",
  validate({
    query:
      getFilesQuerySchema,
  }),
  getFiles
);

/* =========================================================
   FILE OPERATIONS
========================================================= */

router.patch(
  "/:id",
  validate({
    params:
      fileIdParamsSchema,
    body:
      renameFileSchema,
  }),
  requireEditorAccess(
    "file"
  ),
  renameFile
);

router.patch(
  "/:id/move",
  validate({
    params:
      fileIdParamsSchema,
    body:
      moveFileSchema,
  }),
  requireEditorAccess(
    "file"
  ),
  moveFile
);

/* =========================================================
   RESTORE
========================================================= */

router.patch(
  "/trash/:id/restore",
  validate({
    params:
      fileIdParamsSchema,
  }),
  restoreFile
);

router.patch(
  "/trash/folder/:id/restore",
  validate({
    params:
      fileIdParamsSchema,
  }),
  restoreFolder
);

/* =========================================================
   SECURE DOWNLOAD
========================================================= */

router.get(
  "/:id/download",
  validate({
    params:
      fileIdParamsSchema,
  }),
  secureDownloadPath(
    "file"
  ),
  downloadFile
);

/* =========================================================
   DELETE
========================================================= */

router.delete(
  "/:id",
  validate({
    params:
      fileIdParamsSchema,
  }),
  deleteFile
);

module.exports = router;